# Comprehensive Indian Stock Database
# Contains Nifty 50, Nifty Next 50, and other popular stocks

INDIAN_STOCKS = [
    # Nifty 50 Stocks
    {'symbol': 'RELIANCE', 'name': 'Reliance Industries Limited', 'isin': 'INE002A01018'},
    {'symbol': 'TCS', 'name': 'Tata Consultancy Services Limited', 'isin': 'INE467B01029'},
    {'symbol': 'HDFCBANK', 'name': 'HDFC Bank Limited', 'isin': 'INE040A01034'},
    {'symbol': 'INFY', 'name': 'Infosys Limited', 'isin': 'INE009A01021'},
    {'symbol': 'ICICIBANK', 'name': 'ICICI Bank Limited', 'isin': 'INE090A01013'},
    {'symbol': 'HINDUNILVR', 'name': 'Hindustan Unilever Limited', 'isin': 'INE030A01027'},
    {'symbol': 'ITC', 'name': 'ITC Limited', 'isin': 'INE154A01025'},
    {'symbol': 'SBIN', 'name': 'State Bank of India', 'isin': 'INE062A01020'},
    {'symbol': 'BHARTIARTL', 'name': 'Bharti Airtel Limited', 'isin': 'INE397D01024'},
    {'symbol': 'KOTAKBANK', 'name': 'Kotak Mahindra Bank Limited', 'isin': 'INE237A01028'},
    {'symbol': 'LT', 'name': 'Larsen & Toubro Limited', 'isin': 'INE018A01030'},
    {'symbol': 'AXISBANK', 'name': 'Axis Bank Limited', 'isin': 'INE238A01034'},
    {'symbol': 'ASIANPAINT', 'name': 'Asian Paints Limited', 'isin': 'INE021A01026'},
    {'symbol': 'MARUTI', 'name': 'Maruti Suzuki India Limited', 'isin': 'INE585B01010'},
    {'symbol': 'SUNPHARMA', 'name': 'Sun Pharmaceutical Industries Limited', 'isin': 'INE044A01036'},
    {'symbol': 'TITAN', 'name': 'Titan Company Limited', 'isin': 'INE280A01028'},
    {'symbol': 'BAJFINANCE', 'name': 'Bajaj Finance Limited', 'isin': 'INE296A01024'},
    {'symbol': 'WIPRO', 'name': 'Wipro Limited', 'isin': 'INE075A01022'},
    {'symbol': 'ULTRACEMCO', 'name': 'UltraTech Cement Limited', 'isin': 'INE481G01011'},
    {'symbol': 'NESTLEIND', 'name': 'Nestle India Limited', 'isin': 'INE239A01016'},
    {'symbol': 'TATAMOTORS', 'name': 'Tata Motors Limited', 'isin': 'INE155A01022'},
    {'symbol': 'TATASTEEL', 'name': 'Tata Steel Limited', 'isin': 'INE081A01012'},
    {'symbol': 'NTPC', 'name': 'NTPC Limited', 'isin': 'INE733E01010'},
    {'symbol': 'POWERGRID', 'name': 'Power Grid Corporation of India Limited', 'isin': 'INE752E01010'},
    {'symbol': 'TECHM', 'name': 'Tech Mahindra Limited', 'isin': 'INE669C01036'},
    {'symbol': 'HCLTECH', 'name': 'HCL Technologies Limited', 'isin': 'INE860A01027'},
    {'symbol': 'ONGC', 'name': 'Oil and Natural Gas Corporation Limited', 'isin': 'INE213A01029'},
    {'symbol': 'ADANIENT', 'name': 'Adani Enterprises Limited', 'isin': 'INE423A01024'},
    {'symbol': 'ADANIPORTS', 'name': 'Adani Ports and Special Economic Zone Limited', 'isin': 'INE742F01042'},
    {'symbol': 'COALINDIA', 'name': 'Coal India Limited', 'isin': 'INE522F01014'},
    {'symbol': 'JSWSTEEL', 'name': 'JSW Steel Limited', 'isin': 'INE019A01038'},
    {'symbol': 'BAJAJFINSV', 'name': 'Bajaj Finserv Limited', 'isin': 'INE918I01018'},
    {'symbol': 'GRASIM', 'name': 'Grasim Industries Limited', 'isin': 'INE047A01021'},
    {'symbol': 'DIVISLAB', 'name': 'Divis Laboratories Limited', 'isin': 'INE361B01024'},
    {'symbol': 'DRREDDY', 'name': 'Dr. Reddys Laboratories Limited', 'isin': 'INE089A01023'},
    {'symbol': 'BRITANNIA', 'name': 'Britannia Industries Limited', 'isin': 'INE216A01030'},
    {'symbol': 'CIPLA', 'name': 'Cipla Limited', 'isin': 'INE059A01026'},
    {'symbol': 'EICHERMOT', 'name': 'Eicher Motors Limited', 'isin': 'INE066A01021'},
    {'symbol': 'HEROMOTOCO', 'name': 'Hero MotoCorp Limited', 'isin': 'INE158A01026'},
    {'symbol': 'INDUSINDBK', 'name': 'IndusInd Bank Limited', 'isin': 'INE095A01012'},
    {'symbol': 'M&M', 'name': 'Mahindra & Mahindra Limited', 'isin': 'INE101A01026'},
    {'symbol': 'SBILIFE', 'name': 'SBI Life Insurance Company Limited', 'isin': 'INE123W01016'},
    {'symbol': 'HDFCLIFE', 'name': 'HDFC Life Insurance Company Limited', 'isin': 'INE795G01014'},
    {'symbol': 'APOLLOHOSP', 'name': 'Apollo Hospitals Enterprise Limited', 'isin': 'INE437A01024'},
    {'symbol': 'BPCL', 'name': 'Bharat Petroleum Corporation Limited', 'isin': 'INE029A01011'},
    {'symbol': 'HINDALCO', 'name': 'Hindalco Industries Limited', 'isin': 'INE038A01020'},
    {'symbol': 'TATACONSUM', 'name': 'Tata Consumer Products Limited', 'isin': 'INE192A01025'},
    {'symbol': 'BAJAJ-AUTO', 'name': 'Bajaj Auto Limited', 'isin': 'INE917I01010'},
    {'symbol': 'SHREECEM', 'name': 'Shree Cement Limited', 'isin': 'INE070A01015'},
    {'symbol': 'UPL', 'name': 'UPL Limited', 'isin': 'INE628A01036'},

    # Nifty Next 50 and other popular stocks
    {'symbol': 'ADANIGREEN', 'name': 'Adani Green Energy Limited', 'isin': 'INE364U01010'},
    {'symbol': 'ADANITRANS', 'name': 'Adani Transmission Limited', 'isin': 'INE931S01010'},
    {'symbol': 'AMBUJACEM', 'name': 'Ambuja Cements Limited', 'isin': 'INE079A01024'},
    {'symbol': 'AUROPHARMA', 'name': 'Aurobindo Pharma Limited', 'isin': 'INE406A01037'},
    {'symbol': 'BANDHANBNK', 'name': 'Bandhan Bank Limited', 'isin': 'INE545U01014'},
    {'symbol': 'BANKBARODA', 'name': 'Bank of Baroda', 'isin': 'INE028A01039'},
    {'symbol': 'BERGEPAINT', 'name': 'Berger Paints India Limited', 'isin': 'INE463A01038'},
    {'symbol': 'BIOCON', 'name': 'Biocon Limited', 'isin': 'INE376G01013'},
    {'symbol': 'BOSCHLTD', 'name': 'Bosch Limited', 'isin': 'INE323A01026'},
    {'symbol': 'CADILAHC', 'name': 'Cadila Healthcare Limited', 'isin': 'INE010B01027'},
    {'symbol': 'CHOLAFIN', 'name': 'Cholamandalam Investment and Finance Company Limited', 'isin': 'INE121A01024'},
    {'symbol': 'COLPAL', 'name': 'Colgate Palmolive India Limited', 'isin': 'INE259A01022'},
    {'symbol': 'CONCOR', 'name': 'Container Corporation of India Limited', 'isin': 'INE111A01025'},
    {'symbol': 'DABUR', 'name': 'Dabur India Limited', 'isin': 'INE016A01026'},
    {'symbol': 'DLF', 'name': 'DLF Limited', 'isin': 'INE271C01023'},
    {'symbol': 'GAIL', 'name': 'GAIL India Limited', 'isin': 'INE129A01019'},
    {'symbol': 'GODREJCP', 'name': 'Godrej Consumer Products Limited', 'isin': 'INE102D01028'},
    {'symbol': 'GODREJPROP', 'name': 'Godrej Properties Limited', 'isin': 'INE484J01027'},
    {'symbol': 'HAVELLS', 'name': 'Havells India Limited', 'isin': 'INE176B01034'},
    {'symbol': 'HINDPETRO', 'name': 'Hindustan Petroleum Corporation Limited', 'isin': 'INE094A01015'},
    {'symbol': 'ICICIPRULI', 'name': 'ICICI Prudential Life Insurance Company Limited', 'isin': 'INE726G01019'},
    {'symbol': 'ICICIGI', 'name': 'ICICI Lombard General Insurance Company Limited', 'isin': 'INE765G01017'},
    {'symbol': 'IDEA', 'name': 'Vodafone Idea Limited', 'isin': 'INE669E01016'},
    {'symbol': 'IGL', 'name': 'Indraprastha Gas Limited', 'isin': 'INE203G01027'},
    {'symbol': 'INDUSTOWER', 'name': 'Indus Towers Limited', 'isin': 'INE121J01017'},
    {'symbol': 'IOC', 'name': 'Indian Oil Corporation Limited', 'isin': 'INE242A01010'},
    {'symbol': 'IRCTC', 'name': 'Indian Railway Catering and Tourism Corporation Limited', 'isin': 'INE335Y01020'},
    {'symbol': 'JINDALSTEL', 'name': 'Jindal Steel & Power Limited', 'isin': 'INE749A01030'},
    {'symbol': 'JUBLFOOD', 'name': 'Jubilant Foodworks Limited', 'isin': 'INE797F01012'},
    {'symbol': 'LUPIN', 'name': 'Lupin Limited', 'isin': 'INE326A01037'},
    {'symbol': 'MARICO', 'name': 'Marico Limited', 'isin': 'INE196A01026'},
    {'symbol': 'MCDOWELL-N', 'name': 'United Spirits Limited', 'isin': 'INE854D01024'},
    {'symbol': 'MOTHERSUMI', 'name': 'Motherson Sumi Systems Limited', 'isin': 'INE775A01035'},
    {'symbol': 'MPHASIS', 'name': 'Mphasis Limited', 'isin': 'INE356A01018'},
    {'symbol': 'MUTHOOTFIN', 'name': 'Muthoot Finance Limited', 'isin': 'INE414G01012'},
    {'symbol': 'NAUKRI', 'name': 'Info Edge India Limited', 'isin': 'INE663F01024'},
    {'symbol': 'NMDC', 'name': 'NMDC Limited', 'isin': 'INE584A01023'},
    {'symbol': 'OBEROIRLTY', 'name': 'Oberoi Realty Limited', 'isin': 'INE093I01010'},
    {'symbol': 'OFSS', 'name': 'Oracle Financial Services Software Limited', 'isin': 'INE881D01027'},
    {'symbol': 'PAGEIND', 'name': 'Page Industries Limited', 'isin': 'INE761H01022'},
    {'symbol': 'PEL', 'name': 'Piramal Enterprises Limited', 'isin': 'INE140A01024'},
    {'symbol': 'PETRONET', 'name': 'Petronet LNG Limited', 'isin': 'INE347G01014'},
    {'symbol': 'PFC', 'name': 'Power Finance Corporation Limited', 'isin': 'INE134E01011'},
    {'symbol': 'PIDILITIND', 'name': 'Pidilite Industries Limited', 'isin': 'INE318A01026'},
    {'symbol': 'PNB', 'name': 'Punjab National Bank', 'isin': 'INE160A01022'},
    {'symbol': 'RECLTD', 'name': 'REC Limited', 'isin': 'INE020B01018'},
    {'symbol': 'SAIL', 'name': 'Steel Authority of India Limited', 'isin': 'INE114A01011'},
    {'symbol': 'SIEMENS', 'name': 'Siemens Limited', 'isin': 'INE003A01024'},
    {'symbol': 'SRF', 'name': 'SRF Limited', 'isin': 'INE647A01010'},
    {'symbol': 'TATAELXSI', 'name': 'Tata Elxsi Limited', 'isin': 'INE670A01012'},
    {'symbol': 'TATAPOWER', 'name': 'Tata Power Company Limited', 'isin': 'INE245A01021'},
    {'symbol': 'TORNTPHARM', 'name': 'Torrent Pharmaceuticals Limited', 'isin': 'INE685A01028'},
    {'symbol': 'TORNTPOWER', 'name': 'Torrent Power Limited', 'isin': 'INE813H01021'},
    {'symbol': 'TRENT', 'name': 'Trent Limited', 'isin': 'INE849A01020'},
    {'symbol': 'VEDL', 'name': 'Vedanta Limited', 'isin': 'INE205A01025'},
    {'symbol': 'VOLTAS', 'name': 'Voltas Limited', 'isin': 'INE226A01021'},
    {'symbol': 'ZEEL', 'name': 'Zee Entertainment Enterprises Limited', 'isin': 'INE256A01028'},

    # User's stocks and other popular ones
    {'symbol': 'AJANTPHARM', 'name': 'Ajanta Pharma Limited', 'isin': 'INE031B01049'},
    {'symbol': 'PRICOL', 'name': 'Pricol Limited', 'isin': 'INE726C01017'},
    {'symbol': 'CMSINFO', 'name': 'CMS Info Systems Limited', 'isin': 'INE925R01014'},
    {'symbol': 'PERSISTENT', 'name': 'Persistent Systems Limited', 'isin': 'INE262H01013'},
    {'symbol': 'COFORGE', 'name': 'Coforge Limited', 'isin': 'INE591G01017'},
    {'symbol': 'LTIM', 'name': 'LTIMindtree Limited', 'isin': 'INE214T01019'},
    {'symbol': 'LTTS', 'name': 'L&T Technology Services Limited', 'isin': 'INE010V01017'},
    {'symbol': 'HAPPSTMNDS', 'name': 'Happiest Minds Technologies Limited', 'isin': 'INE419U01012'},
    {'symbol': 'ROUTE', 'name': 'Route Mobile Limited', 'isin': 'INE450V01021'},
    {'symbol': 'ZOMATO', 'name': 'Zomato Limited', 'isin': 'INE758T01015'},
    {'symbol': 'PAYTM', 'name': 'One97 Communications Limited', 'isin': 'INE982J01020'},
    {'symbol': 'NYKAA', 'name': 'FSN E-Commerce Ventures Limited', 'isin': 'INE388Y01029'},
    {'symbol': 'POLICYBZR', 'name': 'PB Fintech Limited', 'isin': 'INE417T01026'},
    {'symbol': 'DELHIVERY', 'name': 'Delhivery Limited', 'isin': 'INE148O01028'},
    {'symbol': 'CARTRADE', 'name': 'CarTrade Tech Limited', 'isin': 'INE290S01011'},
    {'symbol': 'EASEMYTRIP', 'name': 'Easy Trip Planners Limited', 'isin': 'INE07RK01013'},
    {'symbol': 'IRFC', 'name': 'Indian Railway Finance Corporation Limited', 'isin': 'INE053F01010'},
    {'symbol': 'HAL', 'name': 'Hindustan Aeronautics Limited', 'isin': 'INE066F01012'},
    {'symbol': 'BEL', 'name': 'Bharat Electronics Limited', 'isin': 'INE263A01024'},
    {'symbol': 'BHEL', 'name': 'Bharat Heavy Electricals Limited', 'isin': 'INE257A01026'},
    {'symbol': 'MAZDA', 'name': 'Mazagon Dock Shipbuilders Limited', 'isin': 'INE249Z01012'},
    {'symbol': 'COCHINSHIP', 'name': 'Cochin Shipyard Limited', 'isin': 'INE704P01017'},
    {'symbol': 'GRSE', 'name': 'Garden Reach Shipbuilders & Engineers Limited', 'isin': 'INE382Z01011'},
    {'symbol': 'ASTRAL', 'name': 'Astral Limited', 'isin': 'INE006I01046'},
    {'symbol': 'POLYCAB', 'name': 'Polycab India Limited', 'isin': 'INE455K01017'},
    {'symbol': 'CROMPTON', 'name': 'Crompton Greaves Consumer Electricals Limited', 'isin': 'INE299U01018'},
    {'symbol': 'DIXON', 'name': 'Dixon Technologies India Limited', 'isin': 'INE935N01020'},
    {'symbol': 'AMBER', 'name': 'Amber Enterprises India Limited', 'isin': 'INE371P01015'},
    {'symbol': 'BLUESTARCO', 'name': 'Blue Star Limited', 'isin': 'INE472A01039'},
    {'symbol': 'WHIRLPOOL', 'name': 'Whirlpool of India Limited', 'isin': 'INE716A01013'},
    {'symbol': 'SYMPHONY', 'name': 'Symphony Limited', 'isin': 'INE225D01027'},
    {'symbol': 'BATAINDIA', 'name': 'Bata India Limited', 'isin': 'INE176A01028'},
    {'symbol': 'RELAXO', 'name': 'Relaxo Footwears Limited', 'isin': 'INE131B01039'},
    {'symbol': 'CAMPUS', 'name': 'Campus Activewear Limited', 'isin': 'INE343S01018'},
    {'symbol': 'METROBRAND', 'name': 'Metro Brands Limited', 'isin': 'INE317I01021'},
    {'symbol': 'ABFRL', 'name': 'Aditya Birla Fashion and Retail Limited', 'isin': 'INE647O01011'},
    {'symbol': 'SHOPERSTOP', 'name': 'Shoppers Stop Limited', 'isin': 'INE498B01024'},
    {'symbol': 'VMART', 'name': 'V-Mart Retail Limited', 'isin': 'INE665J01013'},
    {'symbol': 'DMART', 'name': 'Avenue Supermarts Limited', 'isin': 'INE192R01011'},
    {'symbol': 'TATACOMM', 'name': 'Tata Communications Limited', 'isin': 'INE151A01013'},
    {'symbol': 'STARHEALTH', 'name': 'Star Health and Allied Insurance Company Limited', 'isin': 'INE718B01017'},
    {'symbol': 'MAXHEALTH', 'name': 'Max Healthcare Institute Limited', 'isin': 'INE027H01010'},
    {'symbol': 'FORTIS', 'name': 'Fortis Healthcare Limited', 'isin': 'INE061F01013'},
    {'symbol': 'METROPOLIS', 'name': 'Metropolis Healthcare Limited', 'isin': 'INE112L01020'},
    {'symbol': 'LALPATHLAB', 'name': 'Dr. Lal PathLabs Limited', 'isin': 'INE600L01024'},
    {'symbol': 'THYROCARE', 'name': 'Thyrocare Technologies Limited', 'isin': 'INE594H01019'},
    {'symbol': 'SYNGENE', 'name': 'Syngene International Limited', 'isin': 'INE398R01022'},
    {'symbol': 'LAURUS', 'name': 'Laurus Labs Limited', 'isin': 'INE947Q01010'},
    {'symbol': 'GRANULES', 'name': 'Granules India Limited', 'isin': 'INE101D01020'},
    {'symbol': 'NATCOPHARM', 'name': 'Natco Pharma Limited', 'isin': 'INE987B01026'},
    {'symbol': 'ALKEM', 'name': 'Alkem Laboratories Limited', 'isin': 'INE540L01014'},
    {'symbol': 'IPCALAB', 'name': 'IPCA Laboratories Limited', 'isin': 'INE571A01020'},
    {'symbol': 'LAURUSLABS', 'name': 'Laurus Labs Limited', 'isin': 'INE947Q01028'},
    {'symbol': 'GLENMARK', 'name': 'Glenmark Pharmaceuticals Limited', 'isin': 'INE935A01035'},
    {'symbol': 'ABBOTINDIA', 'name': 'Abbott India Limited', 'isin': 'INE358A01014'},
    {'symbol': 'PFIZER', 'name': 'Pfizer Limited', 'isin': 'INE182A01018'},
    {'symbol': 'GLAXO', 'name': 'GlaxoSmithKline Pharmaceuticals Limited', 'isin': 'INE159A01016'},
    {'symbol': 'SANOFI', 'name': 'Sanofi India Limited', 'isin': 'INE058A01010'},

    # ETFs
    {'symbol': 'GOLDBEES', 'name': 'Nippon India ETF Gold BeES', 'isin': 'INF204KB17I5'},
]

def get_stocks_for_provider(suffix='.NS'):
    """Get stocks with appropriate suffix for provider (NS for Yahoo, BSE for Alpha Vantage)"""
    return [
        {
            'symbol': f"{s['symbol']}{suffix}",
            'name': s['name'],
            'isin': s['isin']
        }
        for s in INDIAN_STOCKS
    ]
