[phases.setup]
nixPkgs = ["python39", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "cd backend && pip install -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "./start.sh"

[variables]
PYTHONPATH = "/app"
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
CI = "false"