[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# Backend variables
PYTHONPATH = "/app"
PORT = "8000"
# Frontend build variables  
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
CI = "false"