[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"
PORT = "8000"